# Imports

In [1]:
import pandas as pd

# Data Dirs

In [175]:
summary_file = '/Users/s236922/code/projects/Kreye-JEM-2021/summary/d3bbcbdd-92b4-4a8b-8c9a-57e263d81932.negative.summary.tsv'
order_file = '/Users/s236922/code/projects/Kreye-JEM-2021/order/d3bbcbdd-92b4-4a8b-8c9a-57e263d81932.to_order.csv'
output_file = '/Users/s236922/code/projects/Kreye-JEM-2021/pairmaster/d3bbcbdd-92b4-4a8b-8c9a-57e263d81932.negative.pairmaster.csv'

# PairMaster

In [176]:
summary_df = pd.read_csv(summary_file, delimiter='\t')
order_df = pd.read_csv(order_file, usecols=['sequence_id', 'to_order'])
sum_ord_df = summary_df.merge(order_df, how='left', on='sequence_id')
print(sum_ord_df.columns)

Index(['sequence_id', 'productive', 'v_call', 'd_call', 'j_call', 'fwr1',
       'cdr1', 'fwr2', 'cdr2', 'fwr3', 'cdr3', 'fwr4', 'cdr3_aa_length',
       'cdr3_aa_charge', 'mu_aa_count_v_r', 'v_identity', 'sequence_alignment',
       'mu_total_count_fwr1', 'mu_total_count_cdr1', 'mu_total_count_fwr2',
       'mu_total_count_cdr2', 'mu_total_count_fwr3', 'mu_count_fwr1_r',
       'mu_count_fwr1_s', 'mu_count_cdr1_r', 'mu_count_cdr1_s',
       'mu_count_fwr2_r', 'mu_count_fwr2_s', 'mu_count_cdr2_r',
       'mu_count_cdr2_s', 'mu_count_fwr3_r', 'mu_count_fwr3_s',
       'mu_total_count_fwr1_aa', 'mu_total_count_cdr1_aa',
       'mu_total_count_fwr2_aa', 'mu_total_count_cdr2_aa',
       'mu_total_count_fwr3_aa', 'mu_count_fwr1_r_aa', 'mu_count_fwr1_s_aa',
       'mu_count_cdr1_r_aa', 'mu_count_cdr1_s_aa', 'mu_count_fwr2_r_aa',
       'mu_count_fwr2_s_aa', 'mu_count_cdr2_r_aa', 'mu_count_cdr2_s_aa',
       'mu_count_fwr3_r_aa', 'mu_count_fwr3_s_aa', 'to_order'],
      dtype='object')

In [177]:
sum_ord_df['subject_id'] = sum_ord_df['sequence_id'].str.split('.').str[0].str.split('-').str[0]
sum_ord_df['sample_id'] = sum_ord_df['sequence_id'].str.split('.').str[0].str.split('-').str[1]
sum_ord_df.head()

,sequence_id,productive,v_call,d_call,j_call,fwr1,cdr1,fwr2,cdr2,fwr3,...,mu_count_cdr1_s_aa,mu_count_fwr2_r_aa,mu_count_fwr2_s_aa,mu_count_cdr2_r_aa,mu_count_cdr2_s_aa,mu_count_fwr3_r_aa,mu_count_fwr3_s_aa,to_order,subject_id,sample_id
0,113-103.heavy.88FJ02_C06,True,IGHV1-46*01,IGHD3-22*01,IGHJ4*02,AGGTGCAGCTGGTGGAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGC...,GGATACACTTTCACCAGTTACTAT,ATATACTGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGG...,ATCAATCCTAATACTGATAACACA,AATCACGCACAGAAGTTCCAGGGCAGAGTCACCATGACCAGGGACA...,...,2.0,2.0,0.0,4.0,1.0,2.0,2.0,CTGCAACCGGTGTACATTCCAGGTGCAGCTGGTGGAGTCTGGGGCT...,113,103
1,113-103.kappa.88FJ01_C03,True,IGKV1-5*03,NaN,IGKJ1*01,ATGACCCAGTCTCCATTCTCCCCGTCTGCATCTGTTGGAGACAGAG...,CAGAGAATTAGTAGCTGG,TTGGCCTGGTATCAACAAAAACCAGGGAAAGCCCCTAAGTTCCTGA...,AAGGCGTCT,ACTTTAGAAAGTGGAGTCCCATCAAGGTTCAGCGGCAGTGGATCTG...,...,0.0,2.0,2.0,0.0,0.0,1.0,1.0,TGTGCTGCAACCGGTGTACATTCAATGACCCAGTCTCCATTCTCCC...,113,103
2,113-104.heavy.88FJ02_C07,True,"IGHV3-30*04,IGHV3-30-3*03","IGHD5-18*01,IGHD5-5*01",IGHJ4*02,AGGTGCAGCTGGTGGAGTCTGGGGGAGGCGTGGTCCAGCCTGGGAG...,GGATTCACCTTCAGTAACTATGCC,ATGCACTGGGTCCGTCAGGCTCCAGACAAGGGGCTGGAGTGGGTGG...,ATGTCATATGATGGAAGCAATAAG,TACTACGCAGACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACA...,...,1.0,1.0,1.0,1.0,2.0,0.0,2.0,CTGCAACCGGTGTACATTCCAGGTGCAGCTGGTGGAGTCTGGGGGA...,113,104
3,113-104.kappa.88FJ01_C04,True,IGKV1-9*01,NaN,IGKJ4*01,CCCAGTCTCCATTCTCCCTGTCTGCATCTGTAGGAGACAGAGTCAC...,CAGGGCATTAGCAGTTAT,TTAGCCTGGTATCAGCAAAAACCAGGGAAAGCCCCTAAGCTCCTGA...,GCTGCATCC,ACTTTGCAAAGTGGGGTCCCATCTAGGTTCAGCGGCAGTGGATCTG...,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,TGTGCTGCAACCGGTGTACATTCACCCAGTCTCCATTCTCCCTGTC...,113,104
4,113-105.lambda.EF01532484,True,IGLV2-14*01,NaN,"IGLJ2*01,IGLJ3*01",CAGTCTGTGCTGACTCAGCCTGCCTCCGTGTCTGGGTCTCTTGGAC...,AGCAGTGACATTGGTGGTTATAACTAT,GTCTCCTGGTACCAACAGCACCCAGGCAAAGCCCCCAAACTCATGA...,GATGTCAGT,GATCGGCCCTCAGGGGTTTCTGATCGGTTCTCTGGCTCCAAGTCTG...,...,0.0,1.0,0.0,1.0,0.0,2.0,1.0,CTGCTACCGGTTCC TGG GCCCAGTCTGTGCTGACTCAGCCTGCC...,113,105

In [178]:
grouped_df = sum_ord_df.groupby(['subject_id', 'sample_id'])
grouped_df['sequence_id'].count()

subject_id  sample_id
113         103          2
            104          2
            105          1
            106          2
            107          2
                        ..
            218          2
            219          2
            220          2
            221          2
            222          1
Name: sequence_id, Length: 101, dtype: int64

In [179]:
field_names = ['Subject_ID', 'Sample_ID']
heavy_names = ['Sequence_ID_HC', 'VH_Gene', 'JH_Gene', 'FWR1_HC', 'CDR1_HC', 'FWR2_HC', 'CDR2_HC', 'FWR3_HC', 'CDR3_HC', 'CDR3_AA_Length_HC', 'CDR3_AA_Charge_HC', 'Replacement_Mutations_HC', '%Homology_HC', 'Nucleotide_Sequence_HC', 'Analysis_Reference_HC']
light_names = ['Sequence_ID_LC', 'VL_Gene', 'JL_Gene', 'FWR1_LC', 'CDR1_LC', 'FWR2_LC', 'CDR2_LC', 'FWR3_LC', 'CDR3_LC', 'CDR3_AA_Length_LC', 'CDR3_AA_Charge_LC', 'Replacement_Mutations_LC', '%Homology_LC', 'Nucleotide_Sequence_LC', 'Analysis_Reference_LC']

field_names += heavy_names
field_names += light_names

pairmaster = pd.DataFrame(columns=field_names)
for sub_samp_id, group_df in grouped_df:
    group_df = group_df.reset_index()
    
    print(f'Processing subject_id: {sub_samp_id[0]}, sample_id: {sub_samp_id[1]}')

    heavy = []
    light = []
    for i in range(group_df.shape[0]):
        # print(group_df)
        # if group_df.loc[i,'productive']:
        if group_df.loc[i,'sequence_id'].split('.')[1] == 'heavy':
            heavy.append(group_df.loc[i,:])
        else:
            light.append(group_df.loc[i,:])
    
    for h in heavy:
        for l in light:
            new_row = pd.DataFrame(columns=field_names)

            # both
            new_row.loc[i,'Subject_ID'] = h['subject_id']
            new_row.loc[i,'Sample_ID'] = h['sample_id']
            
            # HC
            new_row.loc[i,'Sequence_ID_HC'] = h['sequence_id']
            new_row.loc[i,'VH_Gene'] = h['v_call']
            new_row.loc[i,'JH_Gene'] = h['j_call']

            new_row.loc[i,'FWR1_HC'] = h['fwr1']
            new_row.loc[i,'CDR1_HC'] = h['cdr1']
            new_row.loc[i,'FWR2_HC'] = h['fwr2']
            new_row.loc[i,'CDR2_HC'] = h['cdr2']
            new_row.loc[i,'FWR3_HC'] = h['fwr3']
            new_row.loc[i,'CDR3_HC'] = h['cdr3']
            new_row.loc[i,'CDR3_AA_Length_HC'] = h['cdr3_aa_length']
            new_row.loc[i,'CDR3_AA_Charge_HC'] = h['cdr3_aa_charge']
            new_row.loc[i,'Replacement_Mutations_HC'] = h['mu_aa_count_v_r']
            new_row.loc[i,'%Homology_HC'] = h['v_identity']
            new_row.loc[i,'Nucleotide_Sequence_HC'] = h['to_order']
            new_row.loc[i,'Analysis_Reference_HC'] = ''

            # LC
            new_row.loc[i,'Sequence_ID_LC'] = l['sequence_id']
            new_row.loc[i,'VL_Gene'] = l['v_call']
            new_row.loc[i,'JL_Gene'] = l['j_call']

            new_row.loc[i,'FWR1_LC'] = l['fwr1']
            new_row.loc[i,'CDR1_LC'] = l['cdr1']
            new_row.loc[i,'FWR2_LC'] = l['fwr2']
            new_row.loc[i,'CDR2_LC'] = l['cdr2']
            new_row.loc[i,'FWR3_LC'] = l['fwr3']
            new_row.loc[i,'CDR3_LC'] = l['cdr3']
            new_row.loc[i,'CDR3_AA_Length_LC'] = l['cdr3_aa_length']
            new_row.loc[i,'CDR3_AA_Charge_LC'] = l['cdr3_aa_charge']
            new_row.loc[i,'Replacement_Mutations_LC'] = l['mu_aa_count_v_r']
            new_row.loc[i,'%Homology_LC'] = l['v_identity']
            new_row.loc[i,'Nucleotide_Sequence_LC'] = l['to_order']
            new_row.loc[i,'Analysis_Reference_LC'] = ''

            # create dataframe
            pairmaster = pd.concat([pairmaster, new_row], ignore_index=True)

Processing subject_id: 113, sample_id: 103
Processing subject_id: 113, sample_id: 104
Processing subject_id: 113, sample_id: 105
Processing subject_id: 113, sample_id: 106
Processing subject_id: 113, sample_id: 107
Processing subject_id: 113, sample_id: 109
Processing subject_id: 113, sample_id: 110
Processing subject_id: 113, sample_id: 111
Processing subject_id: 113, sample_id: 112
Processing subject_id: 113, sample_id: 113
Processing subject_id: 113, sample_id: 114
Processing subject_id: 113, sample_id: 116
Processing subject_id: 113, sample_id: 117
Processing subject_id: 113, sample_id: 118
Processing subject_id: 113, sample_id: 119
Processing subject_id: 113, sample_id: 120
Processing subject_id: 113, sample_id: 121
Processing subject_id: 113, sample_id: 122
Processing subject_id: 113, sample_id: 123
Processing subject_id: 113, sample_id: 124
Processing subject_id: 113, sample_id: 125
Processing subject_id: 113, sample_id: 126
Processing subject_id: 113, sample_id: 127
Processing subject_id: 113, sample_id: 128
Processing subject_id: 113, sample_id: 130
Processing subject_id: 113, sample_id: 131
Processing subject_id: 113, sample_id: 132
Processing subject_id: 113, sample_id: 133
Processing subject_id: 113, sample_id: 134
Processing subject_id: 113, sample_id: 135
Processing subject_id: 113, sample_id: 136
Processing subject_id: 113, sample_id: 137
Processing subject_id: 113, sample_id: 138
Processing subject_id: 113, sample_id: 139
Processing subject_id: 113, sample_id: 140
Processing subject_id: 113, sample_id: 141
Processing subject_id: 113, sample_id: 142
Processing subject_id: 113, sample_id: 143
Processing subject_id: 113, sample_id: 144
Processing subject_id: 113, sample_id: 145
Processing subject_id: 113, sample_id: 146
Processing subject_id: 113, sample_id: 147
Processing subject_id: 113, sample_id: 149
Processing subject_id: 113, sample_id: 150
Processing subject_id: 113, sample_id: 151
Processing subject_id: 113, sample_id: 153
Processing subject_id: 113, sample_id: 154
Processing subject_id: 113, sample_id: 155
Processing subject_id: 113, sample_id: 157
Processing subject_id: 113, sample_id: 159
Processing subject_id: 113, sample_id: 160
Processing subject_id: 113, sample_id: 162
Processing subject_id: 113, sample_id: 163
Processing subject_id: 113, sample_id: 164
Processing subject_id: 113, sample_id: 166
Processing subject_id: 113, sample_id: 168
Processing subject_id: 113, sample_id: 169
Processing subject_id: 113, sample_id: 171
Processing subject_id: 113, sample_id: 172
Processing subject_id: 113, sample_id: 173
Processing subject_id: 113, sample_id: 174
Processing subject_id: 113, sample_id: 176
Processing subject_id: 113, sample_id: 177
Processing subject_id: 113, sample_id: 179
Processing subject_id: 113, sample_id: 180
Processing subject_id: 113, sample_id: 182
Processing subject_id: 113, sample_id: 183
Processing subject_id: 113, sample_id: 184
Processing subject_id: 113, sample_id: 185
Processing subject_id: 113, sample_id: 186
Processing subject_id: 113, sample_id: 187
Processing subject_id: 113, sample_id: 188
Processing subject_id: 113, sample_id: 189
Processing subject_id: 113, sample_id: 190
Processing subject_id: 113, sample_id: 191
Processing subject_id: 113, sample_id: 192
Processing subject_id: 113, sample_id: 193
Processing subject_id: 113, sample_id: 194
Processing subject_id: 113, sample_id: 195
Processing subject_id: 113, sample_id: 197
Processing subject_id: 113, sample_id: 199
Processing subject_id: 113, sample_id: 200
Processing subject_id: 113, sample_id: 202
Processing subject_id: 113, sample_id: 203
Processing subject_id: 113, sample_id: 204
Processing subject_id: 113, sample_id: 205
Processing subject_id: 113, sample_id: 206
Processing subject_id: 113, sample_id: 207
Processing subject_id: 113, sample_id: 208
Processing subject_id: 113, sample_id: 209
Processing subject_id: 113, sample_id: 210
Processing subject_id: 113, sample_id: 211
Processing subject_id: 113, sample_id: 212
Processing subject_id: 113, sample_id: 213
Processing subject_id: 113, sample_id: 216
Processing subject_id: 113, sample_id: 217
Processing subject_id: 113, sample_id: 218
Processing subject_id: 113, sample_id: 219
Processing subject_id: 113, sample_id: 220
Processing subject_id: 113, sample_id: 221
Processing subject_id: 113, sample_id: 222

# Write File

In [180]:
pairmaster.to_csv(output_file, index=False)